//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courvix_VPN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Courvix_VPN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Checking For OpenVPN.
        /// </summary>
        internal static string Checking_For_OpenVPN {
            get {
                return ResourceManager.GetString("Checking_For_OpenVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Checking For Updates.
        /// </summary>
        internal static string Checking_For_Updates {
            get {
                return ResourceManager.GetString("Checking_For_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Downloading Config.
        /// </summary>
        internal static string Downloading_Config {
            get {
                return ResourceManager.GetString("Downloading_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Downloading Update.
        /// </summary>
        internal static string Downloading_Update {
            get {
                return ResourceManager.GetString("Downloading_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download server configuration.
        /// </summary>
        internal static string Failed_Download_Config {
            get {
                return ResourceManager.GetString("Failed_Download_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Getting Servers.
        /// </summary>
        internal static string Getting_Servers {
            get {
                return ResourceManager.GetString("Getting_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Found
        ///Do you want to download it.
        /// </summary>
        internal static string New_Version_Found {
            get {
                return ResourceManager.GetString("New_Version_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Not Connected.
        /// </summary>
        internal static string Not_Connected {
            get {
                return ResourceManager.GetString("Not_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you close this message box the browser will open with the download link to openvpn.
        /// </summary>
        internal static string OpenVpn_Download_Open {
            get {
                return ResourceManager.GetString("OpenVpn_Download_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to download OpenVPN to use this client.
        /// </summary>
        internal static string OpenVpn_Not_Found {
            get {
                return ResourceManager.GetString("OpenVpn_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve servers from Courvix Network.
        /// </summary>
        internal static string Server_Load_Failed {
            get {
                return ResourceManager.GetString("Server_Load_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Connecting.
        /// </summary>
        internal static string Status_Vpn_Connecting {
            get {
                return ResourceManager.GetString("Status_Vpn_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An unhandled exception occured\nIt has been logged to %appdata%\Courvix\error.log&quot;.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Vpn_Connect {
            get {
                return ResourceManager.GetString("Vpn_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Vpn_Connecting {
            get {
                return ResourceManager.GetString("Vpn_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Vpn_Disconnect {
            get {
                return ResourceManager.GetString("Vpn_Disconnect", resourceCulture);
            }
        }
    }
}
